apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs-express-helm-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/vtb-wanderers63/argocd-gitops-resources'
    targetRevision: master
    path: helm/nodejs-express-webpage # <-- directory where the Chart.yaml lives
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: helm-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
